version: '3.2'

services:
  resurface:
    image: resurfaceio/pilot:2.2.8
    container_name: apollo_resurface
    ports:
      - '4000:4000'
      - '4001:4001'
      - '4002:4002'

  apollo:
    image: test-apollo
    container_name: apollo
    ports:
      - '80:5000'
    env_file:
      - .env
